const actionsDef = {
    CREATE_COURSE: "CREATE_COURSE",
    UPDATE_COURSE: "UPDATE_COURSE",
    LOAD_COURSES: "LOAD_COURSES",
    LOAD_AUTHORS: "LOAD_AUTHORS",
    DELETE_COURSE: "DELETE_COURSE",
    BEGIN_API_CALL: "BEGIN_API_CALL",
    END_API_CALL: "END_API_CALL",
}
export default actionsDef;